#ifndef ECHMET_REGRESS_REGRESS_TRACER_H
#define ECHMET_REGRESS_REGRESS_TRACER_H

#ifdef ECHMET_REGRESS_DISABLE_TRACING
#define ECHMET_TRACER_DISABLE_TRACING
#endif

#include "echmet_tracer.h"

enum class RegressTracing {
	MATRIX_ALPHA,
	MATRIX_BETA,
	MATRIX_DELTA,
	REGRESS_STEP,
	RESULT_ACCEPTANCE,
	MARK_STEP_BOUNDS,
	MARK_REGRESS_RESTART,
	LAMBDAS,
	VECTOR_X,
	VECTOR_Y,
	VECTOR_PARAMS,
	EVALUATION_ERRORS,
	MATRIX_P,
	VECTOR_FX,
	VECTOR_ERROR,
	MATRIX_ALPHA_FINAL,
	MATRIX_COVARIANCE,
	ZERO_DF_MODE,
	SANITY_CHECK_FAILURE,
	__LAST
};
ECHMET_MAKE_TRACEPOINT_IDS(RegressTracing, MATRIX_ALPHA, __LAST)

#endif // ECHMET_REGRESS_REGRESS_TRACER_H
